<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class UploadController extends AbstractController
{
    /**
     * @Route("/upload", name="upload")
     */
    public function index(Request $request)
    {
        $form = $this->createForm(ProductType::class)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            #$product = $form->getData();

            $file = $form->get('saysa')->getData();
            var_dump($file); die;


            #$fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            #$file->move(
            #    $this->getParameter('brochures_directory'),
            #    $fileName
            #);
        }

        return $this->render('upload/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
